name: build

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:

  build:
    name: Build
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3

      - uses: subosito/flutter-action@v2.10.0
        with:
          flutter-version: '3.7.5'
          channel: 'stable'

      - name: Build debug apk
        run: flutter build apk --debug

      - name: Get apk
        run: cp build/app/outputs/flutter-apk/app-debug.apk ecosystem-companion-debug.apk

      - name: Save apk
        uses: actions/upload-artifact@v3.1.2
        with:
          name: Ecosystem Companion - debug build
          path: ecosystem-companion-debug.apk
          retention-days: 2