name: build

on:
  pull_request:
    branches:
      - master
  workflow_dispatch:

jobs:

  build:
    name: Build
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3

      - name: Get NDK
        uses: nttld/setup-ndk@v1
        id: setup-ndk
        with:
          ndk-version: r25c
          add-to-path: true

      - name: Use NDK binaries
        env:
          ANDROID_NDK_HOME: ${{ steps.setup-ndk.outputs.ndk-path }}
        run: /
          echo "$ANDROID_NDK_HOME"
          cd $ANDROID_NDK_HOME
          ls

      - name: Get flutter
        uses: subosito/flutter-action@v2.10.0
        with:
          flutter-version: '3.7.5'
          channel: 'stable'

      - name: Build debug apk
        run: flutter build apk --debug

      - name: Get apk
        run: cp build/app/outputs/flutter-apk/app-debug.apk ecosystem-companion-debug.apk

      - name: Save apk
        uses: actions/upload-artifact@v3.1.2
        with:
          name: Ecosystem Companion - debug build
          path: ecosystem-companion-debug.apk
          retention-days: 2